config/routes.rb
Rails.application.routes.draw do

  
  root 'jobs#index'
  get 'about', to: 'pages#about'
  
  resources :jobs

end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :company_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    def index
        @jobs = Job.order(created_at: :desc)
    end
    
    def show
        @job = Job.find(params[:id])
    end
    
    def new
       @job = Job.new
    end
    
    def create
        @job = Job.new(job_params)
        if @job.save
            flash[:success] = "Job created!"
            redirect_to root_path
        else
            render 'new'
        end
    end
    
    def edit
       @job = Job.find(params[:id])
    end
    
    def update
        @job = Job.find(params[:id])
        if @job.update(job_params)
            flash[:success] = "Job updated!"
            redirect_to root_path
        else
            render 'edit'
        end
    end
    
    def destroy
        @job = Job.find(params[:id])
        @job.destroy
        redirect_to root_path
    end
    
    private
        def job_params
            params.require(:job).permit(:company_name, :job_title, :job_number, :job_link, :date_applied, :interview_date, :contact_person, :contact_email)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jobs/edit.html.erb
<a class="btn-floating btn-large waves-effect waves-light red" href="/"><i class="material-icons">view_list</i></a>
<h5 align="center"><i class="small material-icons">mode_edit</i> Edit Job Listing</h5>

<% if @job.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@job.errors.count, "error") %> prohibited
        this job from being saved:
      </h2>
      <ul>
        <% @job.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<div class="row">
    <%= form_for(@job, :html => {class: "col s12"}) do |f| %>
        <div class="row">
            <div class="input-field col s4">
                <i class="material-icons prefix">business</i>
                <%= f.text_field :company_name, class: "validate", id: "company_name" %>
                <label for="company_name">Company Name</label>
            </div>
            <div class="input-field col s4">
                <i class="material-icons prefix">account_circle</i>
                <%= f.text_field :job_title, class: "validate", id: "job_title" %>
                <label for="job_title">Job Title</label>
            </div>
            <div class="input-field col s4">
                <i class="material-icons prefix">info</i>
                <%= f.text_field :job_number, class: "validate", id: "job_number" %>
                <label for="job_number">Job Number</label>
            </div>
        </div>
        
        <div class="row">
            <div class="input-field col s12">
                <%= f.text_field :job_link, class: "validate", id: "job_link" %>
                <label for="job_link">Job Link</label>
            </div>
        </div>
        
        <div class="row">
            <div class="input-field col s6">
                <i class="material-icons prefix">today</i>
                <%= f.text_field :date_applied, class: "validate", id: "date_applied" %>
                <label for="date_applied">Date Applied</label>
            </div>
            <div class="input-field col s6">
                <i class="material-icons prefix">today</i>
                <%= f.text_field :interview_date, class: "validate", id: "interview_date" %>
                <label for="interview_date">Interview Date</label>
            </div>
        </div>
        
        <div class="row">
            <div class="input-field col s6">
                <i class="material-icons prefix">account_circle</i>
                <%= f.text_field :contact_person, class: "validate", id: "contact_person" %>
                <label for="contact_person">Contact Person</label>
            </div>
            <div class="input-field col s6">
                <i class="material-icons prefix">account_circle</i>
                <%= f.text_field :contact_email, class: "validate", id: "contact_email" %>
                <label for="contact_email">Contact Email</label>
            </div>
        </div>
        
        <div class="row">
            <%= f.submit class: "waves-effect waves-light orange btn" %>
        </div>
    <% end %>
</div>

app/views/jobs/index.html.erb
<a class="btn-floating btn-large waves-effect waves-light red horizontal right" href="/jobs/new"><i class="material-icons">add</i></a>
<table class="striped highlight">
  <thead>
    <tr>
        <th>Job #</th>
        <th>Company Name</th>
        <th>Job title</th>
        <th>Date Applied</th>
        <th>Interview Date</th>
        <th>Contact Person</th>
        <th>Contact Email</th>
        <th><center>Action</center></th>
    </tr>
  </thead>

  <tbody>
  <% @jobs.each do |job| %>
    <tr>
      <td><%= job.job_number %></td>
      <td><%= job.company_name %></td>
      <td><%= job.job_title %></td>
      <td><%= job.date_applied %></td>
      <td><%= job.interview_date %></td>
      <td><%= job.contact_person %></td>
      <td><%= job.contact_email %></td>
      <td><center>
        <%= link_to 'Edit', edit_job_path(job) %>
        <%= link_to 'Delete', job_path(job),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
        </center>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/jobs/new.html.erb
<a class="btn-floating btn-large waves-effect waves-light red" href="/"><i class="material-icons">view_list</i></a>
<h5 align="center"><i class="small material-icons">note_add</i> New Job Listing</h5>

<div class="row">
    <%= form_for(@job, :html => {class: "col s12"}) do |f| %>
        <div class="row">
            <div class="input-field col s4">
                <i class="material-icons prefix">business</i>
                <%= f.text_field :company_name, class: "validate", id: "company_name" %>
                <label for="company_name">Company Name</label>
            </div>
            <div class="input-field col s4">
                <i class="material-icons prefix">account_circle</i>
                <%= f.text_field :job_title, class: "validate", id: "job_title" %>
                <label for="job_title">Job Title</label>
            </div>
            <div class="input-field col s4">
                <i class="material-icons prefix">info</i>
                <%= f.text_field :job_number, class: "validate", id: "job_number" %>
                <label for="job_number">Job Number</label>
            </div>
        </div>
        
        <div class="row">
            <div class="input-field col s12">
                <%= f.text_field :job_link, class: "validate", id: "job_link" %>
                <label for="job_link">Job Link</label>
            </div>
        </div>
        
        <div class="row">
            <div class="input-field col s6">
                <i class="material-icons prefix">today</i>
                <%= f.text_field :date_applied, class: "validate", id: "date_applied" %>
                <label for="date_applied">Date Applied</label>
            </div>
            <div class="input-field col s6">
                <i class="material-icons prefix">today</i>
                <%= f.text_field :interview_date, class: "validate", id: "interview_date" %>
                <label for="interview_date">Interview Date</label>
            </div>
        </div>
        
        <div class="row">
            <div class="input-field col s6">
                <i class="material-icons prefix">account_circle</i>
                <%= f.text_field :contact_person, class: "validate", id: "contact_person" %>
                <label for="contact_person">Contact Person</label>
            </div>
            <div class="input-field col s6">
                <i class="material-icons prefix">account_circle</i>
                <%= f.text_field :contact_email, class: "validate", id: "contact_email" %>
                <label for="contact_email">Contact Email</label>
            </div>
        </div>
        
        <div class="row">
            <%= f.submit class: "waves-effect waves-light orange btn" %>
        </div>
    <% end %>
</div>

app/views/jobs/show.html.erb
<p>
  <strong>Company Name:</strong>
  <%= @job.company_name %>
</p>
 
<p>
  <strong>Job Title:</strong>
  <%= @job.job_title %>
</p>

<p>
  <strong>Date Applied:</strong>
  <%= @job.date_applied %>
</p>

<p>
  <strong>Interview Date:</strong>
  <%= @job.interview_date %>
</p>

<p>
  <strong>Contact Person:</strong>
  <%= @job.contact_person %>
</p>

<p>
  <strong>Contact Email:</strong>
  <%= @job.contact_email %>
</p>

app/views/layouts/_navbar.html.erb
<nav class="light-blue lighten-1">
  <div class="nav-wrapper container">
    <a href="/" class="brand-logo">JobTrakr</a>
    <a href="/" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><a href="/">Home</a></li>
      <li><a href="/about">About</a></li>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li><a href="/">Home</a></li>
      <li><a href="/about">About</a></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Nat's Job Tracker</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% unless flash.empty? %>
  <script type="text/javascript">
      <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
     	 toastr['<%= type %>']('<%= f[1] %>');
      <% end %>
  </script>
<% end %>
 
<%= render 'layouts/navbar' %>
<div class="container main-content">
  <%= yield %>
</div>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/pages/about.html.erb
<br><br>

<h4 align="center">Technologies Used: Rails, Toastr, Materialize CSS</h4>

<br><br><br>

<center><small>&copy; 2016 Nathaniel Giron Productions</small></center>

app/views/pages/home.html.erb
Welcome to Nat's Job Tracker